/aruco_node:
  ros__parameters:
    marker_size: 0.055
    aruco_dictionary_id: DICT_5X5_250
    image_topic: /pupil_glasses/front_camera
    camera_info_topic: /pupil_glasses/front_camera/camera_info
